const seedData = [
    {
        name: 'Free',
        price: 0,
        description: 'This plan includes 1 job',
        features: [
            'Jobs are posted for 7 days',
            'Non-Highlighted Post',
            'Post Jobs Worldwide',
            'Post 1 Job Position',
            'Unlimited Applicants',
            'Unlimited Clicks and Views',
            'Unlimited Applications',
            'Just One Payment',
            'No Credit Card Required',
            'Jobs Live for 7 days',
        ],
    },
    {
        name: 'Silver',
        price: 47.0,
        description: 'This plan includes 3 jobs',
        features: [
            'Jobs are posted for 30 days',
            'Non-Highlighted Job Posts',
            'Post Jobs Worldwide',
            'Post 3 Job Positions',
            'Unlimited Applicants',
            'Unlimited Clicks & Views',
            'Unlimited Applications',
            'Just One Payment per Year',
            'Jobs Live for 30 Days',
        ],
    },
    {
        name: 'Gold',
        price: 97.0,
        description: 'This plan includes unlimited jobs for 90 days',
        features: [
            'Jobs are posted for 90 days',
            'Spotlighted & Highlighted',
            'Post jobs Worldwide',
            'Post 6 Job Positions',
            'Unlimited Applicants',
            'Unlimited Clicks & Views',
            'Unlimited Applications',
            'Just One Payment per Year',
            'Jobs Live for 90 Days',
        ],
    },
    {
        name: 'Platinum',
        price: 297.0,
        description: 'This plan includes unlimited jobs for 1 year',
        features: [
            'Jobs are posted for 90 days',
            'Spotlighted & Highlighted',
            'Post jobs Worldwide',
            'Post unlimited Job Positions for 1 year',
            'Unlimited Applicants',
            'Unlimited Clicks & Views',
            'Unlimited Applications',
            'Just One Payment per Year',
            'Jobs Live for 90 Days',
            'Unlimited Access to Resume Bank for 1 year',
        ],
    },
];

module.exports = seedData;